[theme]
primaryColor = "#1976D2"              # Azul Material Design (accent color)
backgroundColor = "#FAFAFA"           # Gris muy claro, casi blanco
secondaryBackgroundColor = "#FFFFFF"  # Blanco puro para tarjetas y paneles
textColor = "#212121"                 # Gris oscuro para buen contraste
font = "sans serif"


[server]
runOnSave = false