# Generated by Django 4.2.16 on 2025-04-09 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rest.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(unique=True)),
                ('login', models.EmailField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('handle', models.EmailField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.CharField(blank=True, help_text='Formato requerido: IPv4:puerto, ej: 192.168.0.1:8080', max_length=22, null=True)),
                ('device_mac', models.CharField(blank=True, max_length=17, null=True)),
                ('device_model', models.CharField(blank=True, max_length=100, null=True)),
                ('device_serial', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='AnexoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('creado_en', models.DateTimeField(help_text='Ingresa la fecha y hora del documento de los Anexos')),
                ('archivo', models.FileField(upload_to=rest.models.anexo_name_file)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='AnexoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexo_in_registro', to='rest.anexoanexo')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_in_registro', to='rest.anexodocumento')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AddField(
            model_name='anexoanexo',
            name='documento_find',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documento_in_anexo', to='rest.anexodocumento'),
        ),
    ]
